#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 6e0bba5b-f5fb-44ec-a754-5af72bc4af7d
# Source File: D:\Arismendys\Documents\SAPIEN\PowerShell Studio\Projects\CONUSER\CONUSER.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
SwIAAB+LCAAAAAAABACFUkFPgzAYvS/ZfyA9mjC2BdxhXQ86MTu4mTG9mlI+pFpaUsrc/PUWyswW
NV6+r6883st7gLfA1B70cUkNJcOB5+FHrd6AGS85SlZoJfknZAsUU1ED6i5jLgzoBboaVfVk3s7S
rcytyaEU3SHvZm2nuylAVCNzMKgzslbPoGuuJJmOJjg4gf6ZdYHVklzDOE1plPp5lKd+GALz6SwK
/Yjms2nKQrsyHPTk/tU+we5YARnj4ByexJXIrJ0XnLvVPeihd9NwYZOPEUkM1aap2jDO6y+mlxRU
t3XtdGPb2kIOGiSDuJHM2HALtJJ79Q7+vVApFS+2LETcuW6b+0f9F72kUB/+A+UyVrq0ejkiJ9R+
gQtBB1zM71oc2mj+yiUVLWFNSyC3m/VTcre1GpXl4eAHYTjAwcXP8wVXHY9jSwIAAA==#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2020 v5.7.172
     Generated on:       27/12/2022 7:41 p. m.
     Generated by:       Arismendys
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2020
#>



#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
YQAAAB+LCAAAAAAABACzCUpNzi9LLap0SSxJVAAyijPz82yVjPUMlex4uRQUbPyLMtMz8xJz3DJz
Uv0Sc1PtgksSi0pKC/QKiott9DFkebls9JGNtAMAoyFkEGEAAAA=#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Show-MainForm_psf) -eq 'OK')
	{
		
	}
	
	$script:ExitCode = 0 #Set the exit code for the Packager
}


#endregion Source: Startup.pss

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	
	#Sample function that provides the location of the script
	function Get-ScriptDirectory
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($null -ne $hostinvocation)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	#Sample variable that provides the location of the script
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	
	
#endregion Source: Globals.ps1

#region Source: MainForm.psf
function Show-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
s0QAAB+LCAAAAAAABABku8eK7FwUpTlPuO9Q1FRQ8g6qC+RNyHtpJu9CJuSlp2/91cNOEjIhCMU5
Z++91rdSyv/tlPl0lMvNp1v6P95f1nYa/5//if4v+H/+n39//+N//G9zaet2TL9i+y2NdCj/j562
ozgtw/+a1+p/g/+/l//vm/57/f8gn08JC85pBBDDcCbPMf/fF8vwxmEM9wSlBDv+QGWLycCqwwsi
BZXvHNKubaFu2YZx2n0bWYuhW5F/aDdzf//+7j1AEJc8IBJFJ1eN3bVrZBIH3SGa5Ss/OBABACCi
ycIcK/SErCN4BJB8VATdgYWntMfc6nH5gftm//vbgEgGy8JC0QOm7rzLtB1aDlwF2ZIAjwOHEGwC
foIBwoNo0wBx5UAF68LiH5T/jL+ioX3wKNFQjRD33x/SMZiQKhBFm+Pdos3dSHkGF5HsPPt2FHtu
7BC4D95IOCKkq41FiWgVrBHqU8evlYv0u6JxcVgjVT7//myYXo7vLlTiT4L9ySO1qalAQtArionA
BYCD9suvn6rqRmau8Js3K6IsntC+/Nx9cvPAGdFE1RnPsvdqGjGyUYh5ZaO1wxRFYbaOALrqFoxG
+EwWq5dRNzgCyj1GKn7auTXTD/m5J5NkdEAOq27doZN0gQoy/v0dv7w3+Qk41+pn7qY5lwwNmfIG
/Z7H31eIRZ+Rp8IyGqo8LB5nYz0szffjSBNV5KHfXVQJJj+YV2jHv78Cl2J6m5rBxa9zOQoCCll0
OoUjNHQpblhsLlBjZfiII7Qzj6whhK8mOO8VMs2aWgJNvY309rZq1/V/f7o9oHw7b4CxNquBZkTk
6BDZLvJjkQgLLx/luwhzfhE0aPUfeP4J1DhtWZsiz7GNvStiH0yjycobUO7fH5Yd3srT1kXCmKBZ
I4PkRyNlAn2t7L40FyVsX312PCv53VP7qVS2tH8u34ph0klyh5WalzEdqJAsDP77q6jdo4JWDHBI
P6UvTz/L7Kw+q0f8zdezymP1L2wVFnKtj7AqagD1rG/GEhIid7PRP179ismvV+iVyP79jU/bP36x
CxtiUEiMj+sQTkvg8H0QitlB2HNJaIfzAQ5uGYcn2J0D7VZmd0jhmyV0zHfWSjnumeN9/u+vSSMe
fyenS1xzE1nzck/NVjbTBR77yUyVj6yjwVW5AwNI1+bfZwv61mCzqdGHOfpiBu3ub/NM9Xb+N6cV
Y9mZmQt7RXtuqe5tuA0oNN2t6KoktjWkVaOWyMsqkdrrNHj3852JOLRVndhhs6MkwsFWdIBWv/33
p/rUoiHxFR+9Qm4RiZznAM9Q2f56OJmwBt4gI8+ZGjAeyMG36UfBGMl4ms3R+jEzoyYWVApVZycH
2r+/XKQq5vlRdAzt7UHQlhsdGa3ZyAhnQWbsS4cmmmP+dDw6JVV/gq/TbUH8KaEbxG/RbO/vPTbI
J7c/7ywgWHbnnHP+0u6qN+973TXxgDn69mjh6RMxXKjcO/ivHvqLjrgB/UBTEvq9dXlB4v5Wy6RX
/tmyeDOxdxbsijQ4UpqZO1rBRoFrh6W9tYDG1L/yWTDE7/0cAVMA2oqtYWMm2EHsJ23bU/sEqipc
fJxs2UNW+vDvL2FmB1pGq2Nz+tdt34WzVG6g9y9CKG+LI9Lae3HnQEQOREgfp/K56ng6rTFOH/T6
QVL+PQiHlO0agf/9EQI2b5ostmjGjaC3l4He7iflUFd/2J36ETT0Q1nc9tMAHyaItC/q0tWK74MS
m2xEo9b2CEeCxuP6/junMPqzd8K5lx5zKVm9tv0WCl9e1gYYWB6J9lP88Pmwifbcydm3dt0Hg2xc
mIw4ADSq0j6sW2iKFY7v2gRMy8kh82OnKVGGopQbsfLfeRLnORrJZCvdfkwrhy97G9zQ5e/xun+V
fGSKgBH072zVw7Pxvd7K+vieGw+z7X3mjV7jEeELsmStcw20+ieaYI3vhzSz0KQumVNLz19w9RAz
hJaNO8e3ibCRTH4ZcRsiRo32q2+aqX7u7WMjK5d/AjiwH/wY3M9O2XAl5S6XSOY96m6xBmCMdlGF
QvG9C6PlZIeTpwHshXRiDnQnEZP5epYPY2wpqNkN4B8Rolo++kBOo8hkaYS6k6sl09LoGmuNNSVH
Dtjwjo3Wdi16TRomKPVY9cypwB8s9vn3d+VSGXqwE2S5Q/vf53vPXx3EHE0mINjjxLVFU65y5S8s
CrGlW9YmWBtYoslvd6foEgfIhWt8f3bP5f/9fRpw3f3RtBaFrOmBKqppn/jI55OMvZ/2NTHYoJdc
krCL59ulr1sXd5ySCBYCZCOCMsp6kHfSzxSLftUyxvsBR+Aa+o2IX+eT2d884Xu2VB+12P4ASLSW
Qb9SRPa6M/ajqmas9WvgCtoOR45SBZlnXQFhKvH995fhUv7TfUPwO9Lke7nQJ9CD/Y/iVHKNMfgy
6Yu3czjn9sYXR7RA1hF5LZGH+8zzD1BqEgHN9yKfGpT//UGS05JxzyAET2JyP5p3XzuRsH9bQ9x6
txZ1jTc4d9UZLGh8tSUesfLkl2VwZVDCU/T8C6+wvb0n9XUZHTLQoCXF1Ay7Y7/9T0cGNIYKg//h
4J3M8VHnoUIrjXkFZnsmxJuCkvLpK4vCcEkQhPNwJxGFwBCN/v1JomFkFCpAWSY3cAMDJdYE9FF4
voKYL6R4Zy3wmbWHFnOuJJK2UKrzdjEVWckpwX6sWvOxTjjtOeTVNxrEJRrVcikIdlWLViZSxvmB
aW/f5U4rywppXyAJEpiST8SHojsdbYMTZaUTh9E9CCSA/IZuiSKApn9/aUn8IHHdmxd8ljvXx6Ka
wWJTtu92RJgyUK905xHWs1Aijxm+eLMfwqznKmMPpgUxWIzjTPyG6/4U//uLvAYn4/gcVwz/NZ6Z
i3PtGAPRt2ZJTs2DsBPqfmNrjw9zScBIDv1dmPWW1nhJUOkfvpHNl/w1vTqL//760lBPh8QZ9EN4
AbIvRH86CAEIXG0VBmEi9BgK2c/AW6E5EtMXxaDbWfF6mAHW8TUZcy12UiL1ceD899epz6Gd6Ip1
m+AKsIe3TbXv+PX63TgCF+k9CSKUlKVcUdigomkcfVOKjFIwcUvYPY1ctakGwKcc55dUE1or52OT
mIYdX7KgDjTSON/v1CpvcWIpnMVA1vwcw+JH2KGPQJ/FsE3sRiXX57Df46NV4xG+k/Ad9O8PhNtH
enwJ70bChpf7pmCwgnc8B9qbHFKes3WC6H0eT15Ds3YbWEgmwCX1t07M4J8rzfCV61SlKiLvLPwi
I/tlZ02SVreeV+vOVYVe6mwIh7W6UXTAG1Dc48YUmjThZQzfIE+MepOlUKQrC2caGdx3wK6jzttv
TY0ZUC/JQxC3hfBRAUeVhcUVeXhUmt9WtsMcvlJC3N6iGOZCZB/U00s96yACZ5veXEu2PmTv16zn
+u+PD/lfQd3sLkUTIXzHLeu8uExtLs5uRObKjvcKUrzuuybPMm5oN58evLRjnEqSNGZ2z09HNc4h
1lBeP30GRBkFbNnrlG56ghohloTk5DRG3E0Odc4IUlvLsgwFgJjjYUAgY9FlG0n3AHAJ+wS+relo
Hxrq1/fcvPxzL4k3DMDltvSGK7CX4munY+0PjTatSxnSgi0f0ZE6viXd2b+4NzBA7tMoudJaAq58
zZKee7nP66e+7GKl+qt9xtse2A3ceF8M+BkAPvdqMmHGtlCKNPBWX63uMD07KsR2r3OLbuG4nKB/
WmU0HxXja/klrm4u89MlEWhOso8OKM/0SYz7iPYQVNAvmdNPMVkV7LrTj7cQuawhgscJKzOhK3x3
VFmvWCKZv31O6E0fhz9OeSGSKQdNW8fKEkK5C2cku8dlLtsVyKdv5mtFAo1b1ZTmprzJ6H0oQyx2
mbZ7T4lAmfqSnRss3yoABpYznqKxIwaXZP2JUhC5gJ0/I08gtM+5aeekYE25ISwy0dS+IXhYgcyP
D1JW5E9dPPEn/EYDmHgvRRdI/+Ais7X5UQcjmIwYNC7x5EcgQ8I810eOIMdN1moV14NBSpSAxkPe
uKjRI0fz9LGgmBQALgmgd22VS80PgpEjoAGrN8A9bpwXuX1liTeD9vhCkwdR7ilcfcTHDs71c4Lk
yvIoCYD2M8oOulvZ10AMavLmBes1Aoi0sbyI+SzSbdpE2Zb37tg+kaEHsEoA77zpTHKHE2I8D1g9
0A1k44movtBO3WrsqO3iLFmQvlRjPjquLLNfDkSoe30IjW9Qoogeo9Cu4lM2BmsCiZXE4m09Q8jv
tXW1+fuABzUC9Td9htC3JXmTzmVQ3n7jr6oUeAv1qFRZRWMabQfbxBofmXfLwvrriW9q3mIHIvz6
VoF5dCvtd7HgJeAApG1lPX9LqYfGZOG92s94ztmtNGGoLnXkWyvG4eLwGFre7YiSn0mVxFSv5s8K
TD3N0uYsl0su+PTXLduAPxhJm2o4oAYZeGvqSKWmCs1vVs0XYqIA13tqSPZNUhdNAfFfQheDAFlY
xDnL2kO+wLRfg3/tep2lMDcDGFE2aA9YqX0VSftWqrE5wJuGNIXwYe90smsb3qBlmfwbaLSIWKmh
PkUQ+IzYSXdzwQsNbAxGHqwB1H6iEERuuTeMM3z91NTPwX94KEdsbV6dHRBkeEfPEM3TtzEkvbat
Wnbrz41AGzrI6Vca+wqGPx2XbQLy4ynC2rP6fvXh7ZDjgYLCct945tsC+qkWmuRdhtgPpItUuEC/
ntKIfWoi48WkwptBWgz9Bi4V8LUGYxA6k8lqkp9v5+CvIr3MqGvJe6rAloiY/xFI21PT5ld0eMEK
Dj0cO4F24OjqCFs6B3OnGpxcpL2eSW316Asn5gZNpbPpsvN2b6R++FZHOoXpG6AidZSe4yCY0bLQ
SKgp8B0mKJFH2PWUcBgKy7vYbppSoyQ+NpvX44Yqhifj5LO/XkUaseH7Pbd0TuhKBki4LFzqsHC1
0fJjOE908XzE/iCqFf+ymsPrRC1DHQqbZOD2CmAgAI9rkX8WS39zFnHJZQ7610zaGhSap/UNdAB0
GOAsDwIjhgRXdREPhrIUbzL4EbeCQcVYSTtBdfBd2nr1c4jq+H6+mfW6c1Mv9XMjO/iGPprwVsvO
ww6ZbM8vu8OC21fnCkHaLanX5mAavrgFz+zuRqzAuNgM/F7O15ZioJXi9awa2zrEBftNptIvabZY
eHcPyYVMTHUBzv06MLPeCPibXcDEP8NyHmxNIRbLy8qzftU+iIldoIZJi+z9VUt+W/QSeKQgJCRq
GxbB7HdLsc+kEU/Wea3c11wMn3As/O57ftgkshSw3lCmh1f8JWIKkdA40u9Ij76k6sDQr4xUlIsI
uM5jIzOa+2iN7bVyNzbw2+QFNSVX33c6Ws947nLepsJ9s/wZ+qTlE+Vne55/Gpt4FQnmBNTAP04r
IDNSqbPGszXEaPphezfMeU+sAeCSfaPP21bxQ/Mj7tE/8tAa8jWuHjbpXZfgFQ1fGn+7d2cJvk2e
EQWLZP7tIotULP3jT3xYrJB3ZxFNsOYrDpF+rTYCVXHk9RCX8sY6XRSNqfaU93DYSJr37f/9KZsS
nb8vJRk4MPipvk/5Fv/8j806944ZLzqCRbPbT/0MeACdeBE/EPfZv8KlvIobPQMzVJ+UnvWiYP79
nQpaZpDBb6LOi72MX2wjPAWh5iRMy02aYBPYfcp1L1v9dx5bFrrEZcsTFCOY3Qnqw4QF97Ob3LDY
/2ahLnZNfPqFQwloIV1grwEhAyD60dQgMuwgfwUzRBqjpq58oGhC/+JjwnRfx4b751yfRCRJWTxD
DHv1rfAsUT2MZeUonUPNTGojBedd+NIljQrS0HwdcgiUjV0fv3nm2vgA4voEU1D3lPax3WjWsqnA
uqKb6n9/nCbDK6mmsmCnYVHCsLlfZOQKuIa2lWLspyeUCQ4fw6JKfbSP0+KqSFjGPZoXX9/jV281
4QUbA198iWuhgjjQ6cd0GX4vuMQQh0x3+MyLetctST2TPtlYm9ne7eSiuPCBnhhemR6J1Hj9TcB4
Ou8KJuWD+735NCcdFNGSYrAUQsnfLHaF47l3Gt8hqZio+6Znd7kHCWV8WLS4d1IJ8F1dZXOfXysj
7zZ28SQrHRNUiNdl9sb9/u69U11lc+z0Rtf6zB63zxdbcOF+vFBl4R34CF67ws2bT78WC46ALqel
L8SyN7Qo87uffbvuN7UtlL3r2/QIcY3tSHes+PO7wO3xLQ/ScAxvzsGVnaD3l7eFgx9XFwtR2oZu
SVsOZ+gGbfr02KmiVu+cbsRBc/ycbBAIZJbUZsZdmBqkO348gu6tt22flN5ofmYMHM0xR4Wve4Yv
yMuCwiYMtw73dwI/uqgS5L+/G6vQl/7OYkv1pNq/Gijh12f32bNkRuhgpflD95n3fQqgEK/Qrn8q
rxcypNDXpfWPU3/PJKvNwuv/S+IWvOuWrqS98eoe3iujC0xJQTUfLiGOjbIC6l1OZDTq1X3vA78g
B2I3mrlmgfjodo0H588KlmVTanF5dwr21K/RfLby+gJGpQ08jZUiZXcBXZpF4N8bitIJFqnC2WZw
dE7qJWlSR3ZcK2atfFhM+CKkO89I+55bZG2LXzkf95wpWwxPdn6LEqWfZz4So59x3cypPTioNa2O
bXwjIddZF/dmwZJQgImBunmlbuYdtpB6tXfSjNKcsxw6DTIpgnzVRtSAdX3Q0hKVuA8Dx3SwosLq
iLo6hrNyg6hj8jCWk7Klfg9Rztqa0G/W/r2e9dp76jPwO7RMVSDXJX/UAT1UO+tYIAne9mqeDzQM
ygpV08mLGaTjlusQcrhIHUCVU1v4Yhqv9/JRXlJllubTZnj4lvDXQEcTfXsemuJqeHe/MuDPdLdJ
Srt3s4aHOj9yfWg1FGVihpk5hLN+bGES22nduuJ3FpLuQnT62wYXAydYucXMIrjdvSK75lrfF204
3ZejXRBeFnJDcnj4SRS7NFLY+IBxrsCJo4f2BhhezX87ZOBCY0eUdNknpebMmLu+G99rIb7KPnME
od8XMSIFURpdXJ+D41TpeRlpdD4jnNMXdiRKC2sk39l4XaZziuQTboCQonPbMG+usfBniJ5TcUo+
HRotbiJ5PRI2lW4GdByvY8tZHyDdCh08XPzLvkikRUjTXF5faO5FjxLifNMtfrmvqsJfjzzbsETy
vlVm8SWaqXdJnbSUX181SmrCybbFTbBWdJjXuU/SprGtiGXI0TtZZih8J4gsC+MaWAwW8Iw4i3A0
KShhEPmehjGnoQoBbcRJQdue2zcf7ovZD8ln+o4L9KstWbiQ4aLeyTIDd1UPrgWXT7bhNhLpmz1T
y+jHq0evb07SgNOhbiJFFXUCdYhARVDXggGFkqhJGFntT/QnichHSF9fSKCXDXv568YmSCJHiEt0
BETD8UYEmiJN7eam9aUXGag/WwqxOvAGfVQ1OBfIcDp9ruCSKk70DJpWg39/MVqquA+nlMWn4wu6
N0YWXuFjEj04JadKurLN9/qJpQHj1CJXPpVsW0qUTMb7KYXYJl/igaGjS5hv81L0WG2jqEf9YOAh
YuZ5mGNX4ZyPLpAPTTzJ5ywjqGEHQZJ/dkX0BcfH7BWL+wQVdPDBrI/xBkCNIbfu9Syogm/0h8nM
TRQs32EdtYo7BKUPuRG0GQxkis/IMpeKlGO/R7iy68Am4vuBQMLPNcrzUYZKnXR5z+GtAiZOAvDz
beDZrARwZfrLL/q1xL67FRpxk8pDpoNoXqYlYdaoRzjFR7jsLR0axwXOuC3LEVaCaO7zri33Oh2n
2THHRM2D0q7Ls4uol19h0GkX0upmp5tE8pHPkIPio7+z50iF2h7qiyv69wfIHN5z3Papyan694c1
EDZt2fwdpSNqVDI59EKThjSNDaFD9DoH3bqHZ3/kqv22xpUyTnSXPX8A9oJ2SC7XFlLpTV9nwLcK
+7qo2G0t7i1k8IYPTHXIGLMAUhIH9su7/SieSlmpil9ZOWqZxssUw7ynXVWKVxX/ksGn/BwxI8P4
bxY+X3A/fm1bNqhPIXRMEZd5V2/jVPjH5nt2Wy+D6uEpUmS04cJrzBKBrlY2wl3jKrwfapq9oiW9
/tAvcUEyT5PVEznAJ5E0LQ+OT8kHBefVnXxNsFrcqLxYjjp7gZexDp80p2Wy0zZ3lj6UP2a94mJv
vSDBn9dlwnASpSqjyRw/50GXF/dCkgcjEGz98OElAoMzforyWLRJ0MnOkmjETh/rRNXvOEcRelnq
J/mkQWG82jty9faQ5TeBKOrh4GMd7d4PSO5C8oPKvsm8rXgXE+MAcyr+tsb88POu5x8EMaWfcZrX
nV+7F5AhmrznFhxiUOa3kWY4FPC2Zqa3fqpMV2vzhkhJleslf/VkDlpuXdJf7c0qX/rA/PWB8bZS
mUolYeD6Qhv8Ud9khMPiZ5iaiEdodvJjFMKpR5cwm53bAuXM24VZwSSnCG6ar1ZAwWC4GLbU9wtG
dpT4nXG7L3dRufl7sww61d9XT1y8aBfsyvp6JZWbjaO48OfJT9SfA8z0LjPaeiqrdLvG6BQmXWEv
4ic3iAE/Seh9ahGV1n2zc0v37pR6/hiXxd7AwQ/fkL1Pb+NDdR0aHtcmIybZ+hcT7/2sS2lfdIvS
Uzeac3VwTtMbOcm9f7M2+F6tHHRvvBNB7eE4CCMFLF8Snb1DZWuyEt6xtT+06c0Oq1RH+o2dAtHN
RX9CyDY1F15XWBJgDiOi3I+Pf3+roTQGbDhOO4ALBa4V//o6wdDXsQKj6gLIqzWDRhfGt0J+jM1I
6lciVVldBBkJVc5xj4O6vihqu0bxprbY3R66Kgo3Q3eA6K/umHIC43PvmwN+afU9HhSMxIgHCRSr
QtCb0BxBGvdlYslj+eOvyfAv+QrXMXn7LYQxE2DWJwSa+aFT4UjqskqJCGGACEJdo4X3Rr6b3wh/
nziCwSFGi/GkyQ8wXpoxUONUjqFIrMfzOiDBRWLEN1XWPWv3g1tMHZTJVYzJvvd4U8nyUfp96ENy
acd4MKpx1WCElMflI10vbuV3eeT5hdEUhiJvFWTBOcFHVfi0UBXEKtTWLBjqGX6DuHdEV7jy1JO0
HW8GJ6lAWu2qIAS/cLjf1nHAhEJIcJb3eSTI17OCvvoCGII+ZaOIhtO+YeaerGLk4jhZslHfXGSi
Jn6m7133QQJqIfozCBTQSuJXFJyLu3X9g3qu8lr+q0jt2JbmD+ig6BVFcBpuQbsKnz7zJge4xxjD
t7MXz3d7BRUBc0pzuo8DyZ0W4XpfDlBojCkABl60pd5ZCBF4NVdYoTvL583fs9O7nw04GdRzBlFf
YfYyjj0X0zxMBfyOdSo4PCzEo8bIUW4QQIUYlg93ngP6//5SDK2RvmYBe6Ip+01Vhs6D7wa/3hGi
ncSF3kzrqIaQTBQ6u4blX0YPmjFOu+zNclnQcBj10SoPXpKXLb93HxUjgCO/K2L9rTOHkBqfDFem
kopF+K5b6sGl342T3kJ6xy9DC46hjKz2FJRZaroFFeVOkYS5/ZfJUafZE7LMfSu0FQ+FTMEwD1DT
E1NLjJnjnLY50icpZlrAA93o5Rx+TH9Tz7eZ3DU/f0bwOUEewPfg9++vwmlOHHm8fuCzBD8I7DRI
8xRuPF2oNzPTHAf4V12FefLs0Gc+RgrljQ3jfj2hgkLPJtI7m2haXfONX+6l8c+2M+/8xV3hyZe4
pstqDAUyoD/clNxsDRsScVEF7AGrSscWpUhIvKjQ8Y6p9SmgZKQdVOGRf/J/fy9iEPkxSOu3xRNI
s0hrSnp7748EqBz5cxKZCsOVwJ3Y+dN6BPtQ8fCCT4OgiUBC6o6kqIXD0qFEl/VyL7q4cCofY+gf
HloJ3TdsCYf8rtFG55ZFN0zfTfTjxpyJqJ7edPxg/7waFPakGU1oUnjp+1sNku+PN+2C8xAhMAO8
m4HBNum/yXbu+nWjXrdKP41b3uvCtIZ0K0TFYbcnMan6cBsP4+Nf1ph+rM93D1nN59D0PTcn6ZB5
QIpC10yQ4lKIEXWg4NuftFtXDbh9NTc++3GTOi2Jj/tGUdwRRJXqpEyObudw21VpTj749u9kqZWU
64m1CtaH0sTRQC4bPhYQvqPhyc73/c/ne1iuKj34ve/UparL3LggSc3pg1O//LMXuWWos3GWb01J
IuMfHfrQ5R3JbGF9aSG8YpM7tSeCUhphlrZIb9B43jgeoheQdh8kxCfoknhAAqxcd5ltKm0Fm9M3
7R4abcG+emWZqI0TAwQxtH+tTNrsX2CuApWw3G4dNoO7Hz+4f2TrWGY7vZHB7wgk94bZ7oRSyMQL
JF/tTdSqIeot4llJJJC0wLNGxaE5YN3BHjZmnxLot1HIY0IE93VMpYj1jmiggmU++eQtsJtISY0d
eJQl79pISWqP5P5QXk3jfvfB0lsoDVywxy/ihuJd6sC7zutUDy8hxuNlHnP6qLtRPD+ymEjLHqfv
CYSqun/vf3+innWdiDphYl/HPfcwihGU2xN7Xha2c4lewgTBpJnyFt9+0P/mFYG7COuKGopeCdks
Eom9Sn2G63oZqSJ32cZ8G5+BPE5Avx6TTWvrddCv+cGCM8oIVxTeSDj/pC2z5l9aeE5urTaf9E0o
TG3QWfwip2jWvZPl7Z5pNSQI2OAJuJ2PX4ZfgYbyLR+TLniQ1td9sX4nmB/Ofn/eqBxAXAQSTeqe
40M5ooVENdgQlPKz//1JhDJlulXPMAgVdQfmG0vQCrIgN7tuEbbDtdERnq5vmvtpSaqsLG8hjlK+
iqQL7otMFIDsKKNx/i9xncTHjGKaWorRIU6y2stNboIuW2Dje2HgTqoVSpwRf1Vy1xt9FRXP0v0w
NCahIvrt60WLMQWDmYxV4junv0deAJQkCD5b7oMCj19MhnS5XF/rTTMXQfZI1qH69SVGGLlI3Css
sMezqNhJcl8/4G2l1UhfzVDs//6uDn4pkOuZ9ZzHRJjHQuEpw0CRPmscGTzBrbrY5DSsTtKuEQG6
OgRUCzmGsZv7kZ7BHgzAG8jldXp3yttSL821/EYnxJNao5N0Pxf8btW5QVcQhyoq1Bgz8zSzeSj5
iKZZp6o8hRQ1wNKNgQwEbK6jUPT+4zcwg4ZomXsEfj+nwTeU/OoOWQeMmUse5i9cd/vQDckI94r8
nVSfiBE+cbShopCEJpkNzK+qPoC8Vv951lMyWmLRiUD56HAMm9rFtKfCbw6dA6ijoTz4IH7DZirz
+e8ognm0XqlpBh6G7lPVPoz/DBz/O12o895cPw01/t9f075lGgE0KV47qz6u1V29rf0mBmYc6oC+
4Z5R0Bp9iOdgCWr7fONrEkMuousYq/YxG8xMZ//9KQsAzpEv2pucMMYVg6rwgpmFQzwpXVn6GQ2F
YHAf2jFGuUKnx76hKQOgKg/zgAHWfaFNW0sC0iXdS9H2Zcq4pg9tU0W5lkbaa5BcQ0+lKxMeQVaK
4L45WiuuajHbizsy/mMLxlRinF0wbXp5jtBuMsMyt/pyiCMROB/EjoTw3m5mIw3Qh/9e2G5JRPf5
HJp6ZmTgTzn7vP9sMStHwcawpLXdTpk1HDt8HFZkPj/PBP79CeJFz2/2AfwoG9FOCHAm17ZB8s6w
a2SVAGZfDDCXQMOT+0AaNog8S9zaENjrb2KFl1z8hJUeRXTQ7SX8hqrahiSaJrxWGFRPPon2DJ+q
of+tOvacqmFMnCbTYsP+6McXJGrxqjWKPbAXbLCUisS02EMWh/Y9t/0Uzrsw5KvzUQ53szLmACYQ
O1Axyt7Yecai18HumHIQWPgnolMKnlriJ5Z9M7McW/Wnr1W2O3B/e7t3+AKpPfDJ0FyBr/I76EYJ
x0t0wLh8U5IsvDU3I8i8yZh0qGxv1jp2pXY1rIWnz0ZT6xf8ZtbbJgE2//urk+ttVPZyGKbJZUlo
ub2BCOZg5JXC55cf6Z57A75cC+1i9R8B0VU25MLzS75oGxrJa0C2lrEM+7Dav78OyibRq2obzmMd
HH9EI0S6PGfi8di0Lz8bKPtObs7AiI9pV+if1pC/TMFJ6RSUuGf1lfSBa3NUtoH794e7VyzEDKFW
y3adTcy40fKpGYLU9MlGwe8wckIRtLX1rCP0acF0/2X31VjYVkkLqpKRS6vHwwN12b1e74xy5Vtd
+6nmKWKWH8t0i6NACkg+k2K5PzpnuGqebcmAf2at3ViusPtvSghGqGim1Z3VYuxNC1qm/b/PI31s
iJmNVIlq68tTC6xmGWLBtrPyEluaIQtsh3SrW65H0pecACOqhoylQTXKgzvnFEnlfpZDtGL7sqXN
SpDIMb82nuJEcW5eS0u24ov2M0HY4we60kIM2DBxwd/SNUs7leW1MeDNJd4Z+awxokgoiYDwq0Wv
ZzkUim9+eaaZeP63LwmgXyfEy1YmNrhTjqFl87hvmU1Q0pcS2BMcpvauF2GcpOPzgIrrWjOzPPZ/
d7FfRRk/cf6LCbfkWGWKMQZ0mfPM0aIEk81o7U9cXvAH46WqVJhlP+sTy1LBbdqek24KVtSNW7IN
yuVXkZJjZ+RN79tGzktaI8R3/sAUBmuki38B0O8v2Y+vKszhjOdaljNfRjNYqlc+HELVbCqXb2JV
lnVs8uS/uzz9U2Mw0vyipv10Exv+ZHwQco6XJ4lKw9rTFf7M66CWRCkm+xtKh2/82/Z2pkKPNn1h
9tdQbSJDeDlkawEh+4zX5/qZFWZLrPFu51p06TbCNF+x8HUzrb0w8e0XyUhl/gBprSQh3lCg6TZo
P2SF73S9odr7vtp7sYJ3tsTvFTOAJeXAWPyLWXoVkaSlvtnhWHW3pQs6e8/OggzJuxX2KImwxtTx
4fl0LErqW0yhKL/EVTdey0SJbK18rrHsIbh6r9XsYKVGjdGc4fYgmtayayUduz6DpKAIMPDNxHZt
GDCw5MT2yAxGNBNZ/aY25+Y47eV70eyVvT72QuhVtWGD/itR8SaJSU2v1S80vrRzFBpTWQI80vLJ
O2k9n1wFxRuuM0p338RL+JZjs+yl7BfD0a2ICqna6zMBVRzEoAVvuTtnqrZRk6pcl7UHupOLD5g0
F7EYN+Q5MrFJH5EL8JGbvecm6BKqMx9rvm0+U49PLfSoLzdIBuVMT+le/CJai3BZykmcYUttjJGs
eF+QcLSTSBL1Wf6ASZc5Raz8/54sPVicNQG3OSTINkass7lA3ObvN8Z/aBvbi93v/lItZP3Ws3qS
FSbXYq/1b9a/9cZd3o15R7zj8GjffhNr+i3vjYb5j5JZoUFH+bWTnfoxeVbdLfO7YPrhYQobLVG7
wSzWdBC7pSddaJL4sFAqaEwrAlkvDP/+fB9UAht8BGNnIn0Lwlj72gKHWxtZWZ9cPBu0OS1Lt+dp
eDB5qHr7XOVROfJfPl1WL2zG/rkWrjUz89+fydxbW/PfYPxirH4azGXR1qSoTZaXqS0zhMsBxoh+
D+rNytY0tBam8AWNNRtdxmRejoxn4SzPCZX65iwZZHM++2J7a72H5juyldr4z6cKzny8B0pSLcbr
KWKJWd4zJZcteYlrpWfOqhYzmq6IGDhItJWWWz7//WXUjQTeF8JTWa9FhhJ55kGw4vMQQlYnproH
3A5pNEveaqmxInYJJLkY+1pNdW2e2GiriAssZk688ejf38J+K7NVVS1CyMecEuXgHBrFRft6aKDB
6kxxDjtUq2JiT/h+kMGoCVdCFO1WAqEJX4mzqCFMTrs13p0ec7OAa3ZvJ65z+8JKL0NwdLfg7MuN
8B5/vg0OFqPLhffXzfdmC21ktr7dE+kfKolRXz+ESlH+e/zx1RCEwJOzAZo4GvYTGCMcLnokPVH1
mDcARDc4NCjfh5j0FQZOFm9CaF7W8JKfKjdMGfrC2frTlUYLkr8c8mPRSR1kkYm+yudQRMFeXKf+
Opxj1psSzz1k4wdB4gEqtlv2W5uudMMFJgBVkgMdQb2HRJVPG9zUtrykWg3wuR9dC/pwMYnHrmLg
y/aNAfYLCtrK8bM/FEFBy85T7QesOse64KdllwBIF8/ddIxYYJpwF7R9yQEk42LpXFqpQYjqm9x1
MiEmB9mvlxBhQptbJ0enU6rA47oaGAf4fQigbNkPNwowvXRqQU4YiMr8izD//gBtadkrBUols8oX
WSCTwxmpjH0lCDoyZHCmpj8feVOaKLloPrp0l60WuFJgE2x/qbi/rXJ+n5chiZeR4IIg8IEoWFRh
0+QVNl9RPxR6uRhJXOj2KpLXvT8x3AGPvlgJqw04utYbgAHq2sZDr2zQUtfR9HT+ez5kPHd9BLOo
pqsFnHn4Lk/7syhUfSvNxbAqh1dBFxK+gO9G+xlZ5TN+GyIKAi0GLAFYHPSkHOI+Pxf+3/2FQ77O
y0lTAO/QCLSaRc+AXc1jgcrKHs4Oc7k+1bfxipTJaHz9hegHiPeIXvQyCb2NIJile+xHOd6awtHW
SGCklWCIHCMNlqicEG+RNKmDRqcHHDI4iGmwRnex7Kp2Kg0FjrYCV+AAAeSineAqQ4l3OvJC//2h
9Ebu+BsOZymaRXAqJZlKUZSwARTdSIrEJjBDo9kuwL1NHavyD0+LJhMDBjZefuiWmgFXmUgB9sfr
WTRdgqlTQRkFI+FAVdJtV+UDRg8KNidCo/1CPQhyVPUXDQdQS4PAA1YOBW+SdGValhZvCyiqKOHu
++b6gMvAvQPk0QMRnpdhCiair7Hw3K1pF3IfL2AJBVDAjc2GSd2HDnM6ITefN6ECj8fcocQmCusc
HMW9jERXCJGd/dKt9JIIpGCKSVIU4NffmTuAIgleo6jKJw4TKMLfvyXaorVtQ6fkZjz95Iv9yxDd
VhcG0T///qLh5L65wN+nJeHzyA7T2DkvcyPmyVP0dqqQO75KfGHqYkklP0rJfHr5J3W2VWZWO+u/
fh9Lc0S9BPBqb8jQ5SR/EXIC1zrczOdk7qGTSOCZY5DuNqPoHSXZW1+kXSxB9hdJF2mhQsVVoTMO
n0XCplyU9g0NXiZ/ggrAm5iymHb+vCXZ6YqUPYNccna9djC04PATGQw1rjnxI6+VjNqPxO1RwDFV
czWovN5ye6bApr6TVRcPe07ViTpPyEPt95yWGPDCpSr6+atv40j+AprkmR4W4wuqSqPO4gmG2qul
Gp0gs0/Nak+VfR+YdN5cj6c3A5tAvMFpUMqFiAHCoWm4PFMAjg7QDOjd6wORPPN3+Bs3tbdF4A5n
JpU0Xye/E2ayLe2ZDN83//5WPXmX+9vEh0++IRest+ccVNfk1zbANRKPFE0kiqaHL2NZOdsnWPox
rVrBiL0VEf7ni7kIVGvG5fqb2rbOx0NJwAB1KXSc+h7eO2G4zJ2jK7pN1XzrEo2xjhfLU3hDQbQw
IVJIGqPuXoVepA1grWzdNWf9vNcBf6NMENPqx7xNUT2Dcdwd98P+g47nG3j7wOB2Vs6S1Ofk3jCh
4ERaBK6PUn8aAvI6FtB3IaLZegmU92rHlnaxguIUp1Yt+vQZzKIt7I3KjebdFdotVRKLH7U/gJAC
APMPellqlqQ+k68g0R0woySJdt2e9f1q7/3fo4lu0jRmUrVO4J3e2ZccIjt5DZxf+vUztMbl2GiE
u7aXXwbEqw833yqoK2B0xHOMJIMDgpLjwffcluXNsYDLgasiZsJR5UeQZD8QXegOGcBikQ+tkd48
QsSUco4YWB+PQkdoBaAlqItZbvTEMqIkC6nUu7YsbSsLRSkwFpuHdPQvzi3jA9L5yGnkDwA3D+UB
CAArk0LdA79/TEbSw1LMEUJUh0VSIYLgS9GEFvqyZfii2fIFmAoeb+gC9t0Bm02l5Dvzs0oFQxDG
K9A2KXOkEqDIQZBUXMaPYBmkxIEFMSipDlB2NNwt4NezaP0ot3dtQm9OIDl6ZA55IwkCNwLK9xId
x970J3IBVe9RtsEfNWeCx+jRe2ERICSzI1zjGO3TF8q8NVWwM2a8i7orikZ44G3pnIRrUcm9u0A3
kDuRiSF9YwewxaxAGs8HcGJU6jQ12bZVB61f8Xs3Tl2U/O/PPYr0Bx8Rcpz0Zp4LfB9hfpHVBi7H
aCQxT3xW60T84JDkaOR/LB3cDadhTePFcYTeM5aEMBVodQO+SfwrQodm4c953JLed5kWXNYpOgAg
BG5VTfG5kWJ1TMKx++wiPFSHtxw2faNZFncABcXAMhNWpzcQd1+qOQCfUtReoFuTASyGRzENZc90
zhqWIQURpCx93FnVPDsKJAUd6HqxqahdBpU6A5lGq6hFRcG8jjD5/o9U88oKnrkCFBo+jHkn5/ik
0PHpqPoDiN+HoLt4UFLWoFTgoEHKez0cJIet6gYUSNZNY6+QLA+QovOXkeyctQsUANCubRbi+IHU
0ixtQ4GgkR2GLBuDDIFPEB+AeUOvnTYWucbBrlQOSOa5xci4AkgAgTj0u7ZRBAvNIvnsSKzSAowe
hDcMAd9v4EQrMDwt8HTf6B8WEbczLw3FFFghSjror47RB6XCeXTaYPgiz+v1oByI9Kal7Go28EEQ
NJaH1l5pIAWAhUVVHAiBWX6DWzGB5nRQBgrg1KAf9LFcNx6sDqMPpYdczzYZb2rL1M0BO5949WPJ
ltIgeZQ8RuDbQ10W0BVL2n2FUxi4urdDI7IG5tgPBzfuS0emHx4RzvcCGdyzwHnvuXWFk6efIv+G
c38fz3WTReprODinH/q2MfkkUYbLLeTNz2QkCwn2sNqXwInsResdoLu5GZ6MtM2TfjkkGd10CY8v
kZOqq6qTH7aPGftdBX/eWd8zZOI1xwNIZ4+fTZ+4fFmZUUzU3NdN0Pk0kGvF61y086O8/JY5K01V
PmjSUeq/XrrPyKLAC9a5o5f3r6OBDykR+nSSA8WxQQWpb7AqvjEamTpHvtvXIOIufRM553dtdw7p
7vj5DhsvI3bvfHttRtTJDNimkn1RICe+SF66gnoxLj3w0YKs7MZ+pZ5vhD8V7KlZc8w4bdz5m9r2
ccB08UYgQdHVFSkQ2Lj9RSkMwEYjLVQIYgzcwAgPc7QP8p0gs5G0Sn8bmcNRkScSPSrkRjQ0n36r
4Hsc8qXYQuOrQ11xhQ0ctv/5S+PsotStbwN+dg5Q5PVwauMpV8DCpGc8vqXdGIbEsvfgffDyExYV
8mZnk0+DkJMwOVp+nWav9TZZH3RHUEZoClrAv96e8aHvXYFo5r+sxGqCCQqwog3zS+Vd998/AiKX
BGe5+NJgKw6xaGkAPuXkuQ2yY6GC3qXhR6DoElaYRFFbnYw0pjnyzB100UWiNkfgDvRQgzKrZ05A
KIP8ifq9NbXtRyPsez/GOc94LdugZyKibqBaZHNz3aAIokZ2yM/iZUlSGptvdByLmXcLoApRAjsW
UPTkJJrHrn7X5meh0AsFV47upBZPgSCrS0BTrBYdjL+Vkadr51SPX2DeB6xAz2PySczfxaIITf8w
Y9zG7dXo+46qly2Nm4bNUckyE58nhbqTgG2NPJPedLPmh4e8vTEU5Vm2HuqgIpy/+CM3XSVa5tc0
FrmEi52E05/73Yr/nkwAus47CupIQmvrMurT5aiV7dIE7hHrwfTwESG0QVfw9e+skiA93ctSc63/
t4kz2E0QiKLovkn/oXsWj2EEhsQ0oZVKBRERFLoTmKnoYKHQAfn6Tl11+3Y3ebk5i5tTlWOwozTO
CG38I/i8SCUjcXrFIremsuZe571mkqh5XCyTA2LVQS1ItgmyTCwM2Ve+Si+ajovevCQjOACQA3El
CvgItYNePz5EmrtnxKjfWKUavcqs8J2FP8gV8aSU5kRcFVtmZHoL8V2CI1LABhK9SpTIck+hsv8S
FkZMYzvR/G1oR7Jpt0OXYANW8GFlKVAnPOOxjIFH2tLUBg7eZS2U6+wT+U6vRLgyMctvN3fafU9M
ZzM4lW3TE5k0wqBV1iCO7CZ/kjMd0EtyWCdKg9cQdSsmrhnI8rTPYxC0Nkq3tj2HuzTkrg+xu47W
Oa9o9wTyMof/kpLnX4dLgCqzRAAA#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formConsultarUsuario = New-Object 'System.Windows.Forms.Form'
	$Usuario = New-Object 'System.Windows.Forms.TextBox'
	$statusstrip1 = New-Object 'System.Windows.Forms.StatusStrip'
	$toolstrip1 = New-Object 'System.Windows.Forms.ToolStrip'
	$Label1 = New-Object 'System.Windows.Forms.ToolStripLabel'
	$Buscar = New-Object 'System.Windows.Forms.ToolStripButton'
	$Etiqueta2 = New-Object 'System.Windows.Forms.ToolStripStatusLabel'
	$progressbar = New-Object 'System.Windows.Forms.ToolStripProgressBar'
	$Separador1 = New-Object 'System.Windows.Forms.ToolStripSeparator'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formConsultarUsuario_Load={
		$progressbar.Maximum = 96
		$Usuario.Focus()
	}
	
	$Usuario_KeyPress = [System.Windows.Forms.KeyPressEventHandler]{
		if ($_.KeyChar -eq 13)
		{
			$Buscar.PerformClick()
		}
	}
	$Buscar_Click={
		#TODO: Place custom script here
		$servidores = @("NOMBRESERVIDOR", "NOMBRESERVIDOR", "NOMBRESERVIDOR", "NOMBRESERVIDOR", "NOMBRESERVIDOR", "NOMBRESERVIDOR", "NOMBRESERVIDOR", "NOMBRESERVIDOR")
		if ($Usuario.Text -eq '')
		{
			[System.Windows.Forms.MessageBox]::Show("Debe especificar un nombre de usuario.")
			$Usuario.Focus()
		}
		else
		{
			foreach ($servidor in $servidores)
			{
				$progressbar.Value += 12
				$result = query session $Usuario.Text /SERVER:$servidor | select -skip 1 | %{ $_.Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries) }
				If ($result)
				{
					[System.Windows.Forms.MessageBox]::Show("El usuario (" + $Usuario.Text + "), está conectado al servidor ($servidor), con el ID: "+$result[2],"",'OK','Information')
					$msg = "¿Desea cerrar la sesión del usuario (" + $Usuario.Text + ") en el servidor: $servidor."
					if ([System.Windows.Forms.MessageBox]::Show($msg, '', 'YesNo', 'Question') -eq 'Yes')
					{
						logoff $Usuario.Text /server:$servidor
						[System.Windows.Forms.MessageBox]::Show("La sesión del usuario ("+$Usuario.Text+") en el servidor $servidor se ha cerrado con exito.","", 'OK' , 'Exclamation')
					}
				}
				else
				{
					[System.Windows.Forms.MessageBox]::Show("No se pudo encontrar al usuario (" + $Usuario.Text + ") en el servidor: $servidor", "", 'OK', 'Exclamation')
				}
			}
			if ($progressbar.Value -eq 96)
			{
				[System.Windows.Forms.MessageBox]::Show("El sistema termino de buscar al usuario (" + $Usuario.Text + ") en los servidores: 
	$servidores", "", 'OK', 'Information')
				$Usuario.Clear()
				$progressbar.Value = 0
				$Usuario.Focus()
			}
			
		}
		
		#	try
		#	{
		#	}
		#	catch
		#	{
		#		[System.Windows.Forms.MessageBox]::Show("Error de ejecución: $($_.exception.message)","", 'OK', 'Error')
		#	}
	}
	
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formConsultarUsuario.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_Usuario = $Usuario.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$Usuario.remove_KeyPress($Usuario_KeyPress)
			$formConsultarUsuario.remove_Load($formConsultarUsuario_Load)
			$Buscar.remove_Click($Buscar_Click)
			$formConsultarUsuario.remove_Load($Form_StateCorrection_Load)
			$formConsultarUsuario.remove_Closing($Form_StoreValues_Closing)
			$formConsultarUsuario.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formConsultarUsuario.SuspendLayout()
	$statusstrip1.SuspendLayout()
	$toolstrip1.SuspendLayout()
	#
	# formConsultarUsuario
	#
	$formConsultarUsuario.Controls.Add($Usuario)
	$formConsultarUsuario.Controls.Add($statusstrip1)
	$formConsultarUsuario.Controls.Add($toolstrip1)
	$formConsultarUsuario.AutoScaleDimensions = '15, 29'
	$formConsultarUsuario.AutoScaleMode = 'Font'
	#region Binary Data
	$formConsultarUsuario.BackgroundImage = [System.Convert]::FromBase64String('
iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAA7DAAAOwwHHb6hk
AAAAB3RJTUUH4wESFhwOghDasAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA
ABpJSURBVHhe7Z0J1DRFdYaRKKIiigsoqyAqCIoKGgQhgmgAcUNBjSwuoKK4oSgQgYC7khglGHEl
KrhB3CKuENwIEHFHjxq3AO4SVgUR4/sgpZ3OnW96Znqpmn6fc55z/jP/fDM91VV3eqqr7l3FLAU3
khvIneQT5d/K18tT5aflF+V35U/lJTd4nfzfG+Tf6XGew3P5G/6W1+C1jpD7S95jfWmMGYCbyx3l
c+RJ8svy1zIN5r68SvLeHAPHsoO8mTTGtMiqcnt5rPysvEZGAzIHr5Yc4zFyO8mxG2NmhIGzs3yz
5JI8GmwlyLG/SfKzgZ8pxpgVWEceJb8vowFVsnwmPhuf0RhT4W6Sb3suoaPBs0z+RnJVcFdpzKhZ
T54or5XRYFlmufPwDrmuNGZU3FgeKplJjwbHmLxSPl/SJsYsPfeUX5HRYBizX5JbSmOWlv2kv/Un
y/wAawqMWSpWk2+XUae3/9+3yptIY4rn1vIsGXV0O9kz5K2kMcXC4D9XRh3cTvd8eRtpTHHcUrKh
JurYtrnnyTWkMcXA79ePy6hD29k9Xfo2oSmGE2TUke38Hi+NyZ69ZdSB7eLuI43Jlo3l5TLqvHZx
aVva2JjsYAvvv8uo49r2PFN6a7HJjmfLqMPa9n2mNCYb2NXHppaos9r2pa29i9BkA3v5o446tCTh
ILHnW+SLJZNou8sHya3lFpINOPybx/i/fSXP5W/421yTk7xRGjM4m8kc9vOTfosMvofJXeRasi14
rQfLw+Vp8mcyOoY+pc2dVMQMzvtk1EG7lp1zn5IvlPeSfU6M8V73lrw3x8CxRMfYte+WxgzGhvJ3
MuqcXftOmQsny+gYu5arANcoMIPxChl1zD7kWzeHjTJseBqiLkHyJdKY3rmpHPq3MLceh4YEHtGx
9eXPJefCmF55jIw6ZJ9+XQ4NxxAdW58+UhrTK++RUWfs223lUFD9Jzqmvn2XNKY3Vpe5rPknfdZQ
5JLmjHPBOTGmFx4uo444hKyKGyJ1Fu+ZU4LTh0ljeuGfZNQJh/Ig2RTuHGwi0wpA5N88NsviId4z
OpahdL4A0xvfkFEnHEpy6tfZSD5KUlX4Q5LJuiY/Wy6TPPeDkr9lgo31DnV4z+jvhzKHCVEzAtaW
v5dRJxzSR8gnSsptXXTDY216oeS1eQ/eK3rOkHJObi+N6ZS9ZNQB7fA+WhrTKa+UUeezw/syaUyn
ONtvvn5UGtMpbLuNOp8d3oulMZ2xjow6ns1HTwSazniAjDqdzcf7S2M6YX8ZdTqbj64dYDqDhTFR
p7P5eLQ0phPYdRZ1OpuPLFYyphNc+CN/yWRsTCd8S0adzubjBdKYTrhERp2uVFk/n+O+hkX8lTSm
dcg7V8pguU6yY/EUyfLYAySFP8ijv4Fk2+9qMsG/eYz/4znUFThQvlySeptvVV4zeq/c5Bw5R6Bp
HUpRRR0uBxmcX5BHSgp4dJEghNd8iDxKni1zDgguG2ZaZ3MZdbah5JuOCa+nyjvIvrmjfJo8Q+Z2
ZcS5MqZVSL4Zdba+/YV8tdxU5sJd5HHylzI65r4dMlGqWVJ2lVFn60sG/ovkzWWu3EJSJ+AnMvoM
ffnX0phWeayMOlvXkvTzCMngKoU1JBWGh0oayrkyplX4rR11ti6l8Cgz86VCLkEqFkefrUs5V8a0
CpVwo87WhZS7IqHnskCqLn7CRJ+1Cw+VxrTKS2XU2dqWjEPkHVg2uFPxCRl95rblXBnTKuSdjzpb
8tLgsVnkVhoLb/5CLit8NioqL3rbcFpbu0aAaZ23yaizJZn0ih5v4hVyTBltyazMZ47aoolMikaP
JzlXxrQK20yjzpbcRv5r7bEm/pfcQo4NqhF9T0ZtspKnSdo6+r+ktwSb1mFdfdTZklvJ28lZkoae
Kyk0MlZuKz8vo7aJZHKU+ZF7VR6LPFka0yrckos6WzJ9i+8ur5XRc6pytZDzop6+oA0+IKM2qkqb
7iaBto6ek+RcGdMq0y7v7yYT+8rfyuh5bKJhlnpVaf4Ik4PsWpy0wega+QSZoK2j5yU5V8a0CgU2
o86WvLOssqOsJxDhEtbLVCfDcuv6eoFvyh1kFdq6+py6H5bGtApVZ6LOlowq6N5Y7iEpJ/ZcSWlu
szK00fMkbfZQSRvWoa2jc5A8XRrTKp+UUWdLsj3W9MO03AwsODKmVdj3HnW2pCvS9Ad3TqJzkORc
GdMqZ8mosyV9ed8ftHV0DpKfkca0Ctl3os6WHPP9/L5hX0F0DpJODW5aZ9okYMnbdktjIxmdg6TL
hJvWmbZYJacUXcsOmYujc5D0OgDTOu+RUWdLsrbd9MM9ZXQOkqQyN6ZVTpRRZ0uy8Mf0w04yOgfJ
f5bGtApLVaPOlnyMNP0wLT/jS6QxrXKIjDpb8iBp+uFgGZ2DJKsujWmV/WTU2ZKuS98fx8joHCTZ
jGVMq1BbL+psyZOk6Yd3yugcJJkjMKZVNpZRZ0uS2ML0wzkyOgdJ1gkY0yrsSlsp0QeZgEw/rFSC
jDwMy5xY1QzItBx2t5amW0i7FrV98jvSmE74iIw6XZJ5AtMtJFSJ2j7Jik1jOoH7y1GnS1I9yHTL
tJTgfyeN6QRy90edLvleabplWq3BPaUxnTAtF93F0nTHjeS00uObSGM648cy6njJzaTpBjZcRW2e
5NwY0ynT6gM8Q5puYIlv1OZJ7wI0nTNtHTrpw003kO03avOk92OYzrm7jDpf8jdyDWnaZU15tYza
PFktzmJMZ3xXRh0wubc07UJloKitkxRZNaYXXiejTph8vzTtMq002z9IY3ph2s5ALlWpfGvagZoL
1AeM2jr5QGlML7AxaNr96GdL0w7TkrGw/sIbgEyvvFZGnTH5dcnCFbMYtCEFQqM2Th4njemVbWTU
Gau6EvDi7Cajtq26lTSmd74iow6ZpKCoWYxPyahtk+dLYwbhABl1yqpbSzMftF3UplWfJI0ZhJvJ
lbLToMtUzc/HZNSmyUvkzaUxg/EKGXXOqttJMxs7yKgtq1KrwZhBIUXVFTLqoMmzpe8INGdVOS3x
55XSFZlNFky7JYjUFTDNeLKM2rDqq6UxWXBHyTdS1FGT7FVfS5qVuY0kw3LUhkmuuNaRxmTDtGo1
eIo0KzOtCjMeKY3JCrYAT8sWhI+TJmbajj9k2e8tpDHZwT3pqNNW/ZVcT5r/y/qS23pRm1V13T+T
Lcz0nyWjjlv1E9J3Bf4MbcGqyaitqp4h3W4ma+4qp2WuQeev/zPT6i0gbeqEq6YIDpdRJ676e8lv
3rGzl6Qtojaq+gJpTBGwkKXJTwHyB24rxwo7Kq+SUdtU/Zz0fn9TFJQTv0xGHboqiUXGWM76TnLa
/X68VPJcY4rj4bLJ5e0P5Zg6+QaSJJ5RW1Sl7VzqyxTNa2TUueuOJQhwu6/J4MeXS2OKhvyB3PaL
Onhd0o0zQJYVPtu0lOpJioD4d79ZCm4pvyqjjl73InkfuWzcQ3KVE33muhfIW0ljlgYm+i6UUYev
e7l8qFwW9pB8puiz1v2R3FAas3RsKvmGjzp+3d/JF8nSeY7ks0SfsS5tQwl2Y5YW6tdNqylQ9a2y
xM0vbI56u4w+UyQbqVhFaczSQxBosnMw+X25vSyF+8pvy+izRP5MbiGNGQ1byiYLYZLXSvbB5zwz
zh2PoyTHGn2GSK6GPPjNKOG+PxWEooExyfPk/WRu/KX8Txkd8yS/Jse4CtKYP8Fv5Y/IaIBMkhVy
75B3kENDOrQT5XUyOtZJsjbCt/qMEVw6nyCjgbKS7DU4TLLOoG/WlEfIprf3qh4vvcjHmBoHSXYI
RoNmJckyRH4BEmp2DWXPyX/YJHtP3V/Lp0ljzASYHGy6arAu38avl/eSbXNvyTf3tBoIk6SO4t2l
MWYKq0tqDTTZSTjJL8lnSXbezQsr8ljI82UZvUcT+Qx/L28qjTEzQHnxpuvnV5IrCkqYsbx4XTkJ
/o/nvFIyQx+91iz+QD5YGmPmhOKXx8p55gYm+XPJtzoz8STj5N88Fj13Hvmtz5wExVONMS3ApTy3
/qIBl5Pc0txEGmMmcHv5KsneeFYDvl9uLpvAJfXnZTT4hvSz8kGyCXzWUyWfnTagLWgTY5YaLufZ
4Ueeu/oA4hKfCbemPEDOuoCoCwlGD5NNIKf/U2WUCJTaisw9sL7AmKWChT7c/26yAei9cpb7+WwS
ouZgm3ME0+S9Tpb3l02hGtKnZPR6Vdkb8HR5E2lM8ewiZ51R59J41mSYLKvl2/V8Gb1mG5KphyuY
28lZeLT8pYxec5LcQaCkuisBmSLhEv1sGXXupjI3ME92HBbcUEjjTPlbGb12E/lbynE9X85TlYeN
PvzWj167qefIB0pjioDB9yEZdeZ55Pfy0XLe9f5cGewmqVbEzwv26Uer+XiM/+M57C/YVc77e5xj
Zblwk6IfTf2oJK+gMVnCb9w3y6bpr2aV+/R8E7eVHYiVeezkw9V4oAU4No7xFzL6DIvKjsOTpHMG
mmzgG5b89W1+260kG39eJlda0dc3BD/agGOLjrltmYQ8Tvax+cmYEL5BnydnndxqS7LufFg+Urb1
DT4LfP5HSW5FzpIBqE3/RzIp6RWHpjco/ElVX2apo045hKwr4Fbg3rLLBTW89mPlu2WTuod9Sbr1
p0jnGDCd8hDJLruoE+Yiu++47cjmnzZ+JvAaaXPQIrsT+5DblNRjNKZVqNTDppmo0+UsP08W2YNP
ss6hfuIsIuXEt5PGLAQlvlnxNmu+u5z8jJwX1vdHr1mKH5BN91gY8ydY6UZCjmtk1LFKkyxDs8Lf
RK9VmkxQvknmdNfEZArrz9mQw+xy1JlKlVtms0IWn+i1SpXbtMxlDJFA1RQAO9qa1q0vTSrvzLK5
hs1Ls5QvK8mLJXsmfMfAXM82kt/JUWdZJmeZHX+EjF5jmWTTlPcYjJj15TwFLUqVCbGmfFBGr7GM
skXZpclGBOvVyVdH3rqoQyyrTIY1qSS0tlxkB2GJ8nn5MnBWoiWGFXzsL1/W37ZNPEROg8080d+O
QYqdsLTYKcyXDHLVUZgiOulj8htyGvMWJVkmvyP3kqZwNpU55M3LSWr3T4L/i/5mrJIMxfMDBULF
XdbCXy2jEztm3ym3niD/F/3NmGXuhEVhrmRcCNzP/5GMTqa188qeCBaJMZdkMuRu8iwZnTxr25I0
6C5ymhGscGPmts+02HbcctuQZcW+WzAwW0lmtqOTZG3X0ve6KMVuGkBmGqrJRCfG2r7kyvPJ0vTI
UTL37DR2XNInTQ88U0YnwNqhpX6D6RCScfqb3+YsX1CmA1iRNbYNPLY8WTi0szQtQlltMr5GDd6n
JJOg2KfN1yYVmLuWykhUXDIt8UYZNXTfkjHI5M33ZHTu+pZahq5s3ALbylx+9zsA5E8uAQAPkGYB
WHd9rowadwgdAPInpwBAfgEyTJs5OUhGDTuUDgD5k1MAwDdIMwdM/OUwoVPVASB/cgsAlIufpy7D
6HmBjBp0SB0A8ie3AIDvl2YGSNxJLvuoMYfUASB/cgwATGJ709AMPFdGDTm0DgD5k2MAwFOlaQAV
W3I9iQ4Aq6xyM0mdPa7SciTXvsNcwJ2lmcKeMmrAHBxrAKDU9tvlT2VqCy5r2Q/fpNZAn+QaAJDc
gmYKOaf1GlsAIBEmE1hRWyAZl2epOdgHOQeAyyQJa80E7ipz3u2XSwC4n7zPH//ZGVzmf1NG7YD/
JnNMiZVzAMCnSDMB8qxFjZaLOQQAsh5fI/lN+XK5mmwbXvOLMmoDzHXwQ+4B4D+kCaAkdW4Lf+oO
HQD2kAz+6jF9SbZdvOJwWX2PqjkPfsg9AKCzCgfsLqPGyskhA8A6clKhE/LSPU+2kbN+dflzGb0P
O9yaDP4hc+eXEAAoTmtqvENGjZWTQwYArpD4to+OK0mpawbwIuwqo9emTFaTwU8BVu4WDHWVUEIA
+Lo0Fei0l8qosXJy6J8AXOpPq3/wYrkIJLeMXpdbftOCy76SuQmeT6mxISghAODm0tzAI2XUSLmZ
wyTgtFWSpErfQM4Lu9ei10VWs026vN9HpsGPD5VDUEoAWDRQLxUnyaiRcjOHAMAA5HI8Or7ku+W8
vE5Gr5kkQNSDQH3w40PkEJQSAChXbwSdqbrCLGdzCACwnvyVjI4x+VdyHiiAGb1e1dMkS4Jhb0ki
zPpzhlr2WkoAQOpZjh4WtUSNk6O5BADYS9ZvCVZlwpB9FbNybxm9Xt3z5GGy/s2PF8qh8uGVFAAO
kaPnGBk1To7mFACAlZPcmouOFV8mZ+VOcqXA0sSXyKEoKQBw7kbPSivOcjO3AJBgDcW3ZXTMx8qm
MPh/IKPXaSprCG4rh6KkAMCEbc6LqjqHnWQlVfrJNQAAy3cPlWw4qR93kyDQxuDn5wCrFYekpACA
O8rRQlXVqFFyNecAkGBiKVpSvVIQaGPwU7XpcXJoSgsA/AQeLdyuiholV0sIADBLEGhj8LOFO5eU
V6UFgC/I0XKRjBolV0sJANAkCGwkpw1+fqIdLB8uT5SflNwBIBcAuxEp3JITpQUAbqGuKUcH94mj
BsnZkgIAcJeAeob1z/EquaGcNlgY/M+QJVFaAMChFk0NypNk1Bg5W1oAgElXAtP2XjD4nyZLo8QA
cKQcHW+TUWPkbIkBACZdCUyyxG/+RIkBgBwLo4PBFDVGzpYaAKBpEGDwP1OWSokB4JdyVJWEqZ0e
NUTulhwAmv7mL3nwQ4kBADeVo6GU7b91Sw0ATW/1PV2WTqkB4AlyNLBWPGqE3C0xAMxyn796i3Ar
yf39j8uSvp1KDQCvl6PhYzJqhNwtLQA0ueyvyy1CdgTyuzQ9xnbtUhJZlhoAPitHw6Skk7mbYwDY
RLJI50DJ3vxtJDkWmi7yifIKRGnHmEC8i8ydUgMAt2VHMRFIx4waoARzCQAMcPLvkVwyOs6fyGkz
/uk+/6R1ApElBIFSAwByxbb0PEJGH74EcwgAt5OfkdHxNTUN/sRmMgoCX5MPlGQbTo/lHgRKDgBD
5VHsFZIhRh++BIcOAGvL78jo2JpaH/xAmbFLZP2575NANuBPyPR4zkGg5ABAQZal5z0y+vAlOGQA
4PfhmTI6rqZGg59v/2jwJ18ooZQgUHIAOEUuPefL6MOX4JABgAm+6JiayuCP7vPXswCTS5A8DT+q
PFZSECg5AJAda+k5V0YfvgSHDADsG4+O6VsySsxZ97cyStV1gKw+L5Wt2lj+UKbHSwkCJQeAc+TS
81IZffgSHCoAMHCvk/XjYT0FA3J72eTW6t/IOvy0OEGm51wlmfiDEoNAyQFgyGSqvUEewMtl1AC5
O1QAIMd//VjS4E+wWo/jqz+v6itkRBQEdpJQWhAoNQCQy5ECsKPgCBk1Qu4OFQDqt05Znlsd/AkG
K2sAqs+tSlWfScwbBKoFS8nwNHQnLjUApDYdBXScr8qoIXJ2qADAQEzHMGnwJ7ilR4LO6nEnXylX
YpYgQFEQKhbXy5QNvZuwxADwZTm69OBcLpb2U2CoAMD9f96fS+6VBn9iUrKVJ8ppzBIE6gVEmKe4
rxyS0gLAFZJbsaNkfxk1Sq4OFQDgUTLV41sJJvqiuwI8tq5swrQgUN0olGTwcz6HprQAMKptwBHH
yahhcnTIANCEx8tJtwQp7T0LURDYWfI4l6zV185l8ENJAWDSpOyoYGPLu2TUQLmZcwCgKMekwc/g
ZdfgrNSDAGsJqguEMKfBD6UEgH+RtK8RVLGlQaKGyslcA8BKg58BSiXheakHgfprN5lX6JMSAgAF
cZhANRUIAm+RUYPlYo4B4DEyqs+PTDCRfm1RCAJkrKm+dm7f/IncA8Cb5Dxl20fDcySdK2q8oc0t
AKwvo8FPQo+3Sv6/LQgC/yh5fWb/cxz8kGsAYC9GWmZtpvBYybdX1JBDmuMVAMuAnyWPlgTPh8lb
yK7YXDa9mzAEOQYAbndzpWZmgEw1kzLeDGXOk4Dmj+QWANistYU0c7CGpCAll09R4/atA0D+5BIA
6LMsve7yamw0PFj+t4wauk8dAPInhwDArdJdpGmRW0lmoifNePehA0D+DBkA6JuvlaMs990XrJuu
bkPtUweA/BkqAFBE5R7S9AC3pJhVvUBGJ6MrHQDahdWJ+8jd5Go8MIG15KMladHIirwSfQeAb8g9
pRmAlB//uzI6OW3rANAepCKr7iZkezi7HutsLas5DtiItKOcRF8BgOzMbOShD5qBuYncT35FRier
LR0A2mE9ebWsty+Ll+rUNx4hFY8mraPvOgBwPHzpeClvpjD7errs4tahA0A7cDkftS+Dt8qt5aTz
yLbkiC4CAMfwUfkgaQqByUK2Gv9MRid1Hrm9w+9Wu5iHyqh9qVNYfd52MnoeUkWn+txkm7eLKYr6
GjnahB3LABsvuCp4n2Q7a3SirU2yD4VSaOyg5KelWSLISHyQpMLOpO2zdnzSF8htSN8YTWbescOM
M2WyFi20acuVc08fiO4+mJGwpYw6h11+Ofdm5DgAjFcHAOMAMGIdAMz1m4xy2W5s+5NzzjoDY66v
thN1Eru8sljMmOthaeqk8tt2+fy8zDmtmRkANnWwnZNlqiwCyd2caiuyByM6xtzk3HKOvYHHFM+P
ZTQYh/BCaYzpCVY0RgNxSL2Czpie2ENGg3BId5XGmB44RkaDcEiPlMaYHshx/8KnpTGmY1aXlP6K
BuGQckwcmzGmQ6jRHw3AHFwpV58xpgWOldHgy0HqExpjOuQcGQ2+HGQ1pTGmI1iynPPGJdJpeYmt
MR1xsIwGXk4+XRpjOoC8ddGgy0nKthljWua2csjCqE0l8zKlvIwxLfJkGQ24HN1fGmNa5GwZDbYc
/Zw0xrTEPWU00HLWpbKNaYk3yGiQ5ezx0hizIGvIy2Q0yHL2cnlLaYxZgKfKaICV4IHSGLMAJScr
JfmmMWYBrpTR4CpBfroYYxbgAhkNrhIkc7ExZgGeIKPBVYKPl8aYBdlXflNSxz4aaDnJMXLVso80
WbPKKn8At5LVLM996J4AAAAASUVORK5CYII=')
	#endregion
	$formConsultarUsuario.BackgroundImageLayout = 'Center'
	$formConsultarUsuario.ClientSize = '562, 468'
	$formConsultarUsuario.FormBorderStyle = 'FixedSingle'
	#region Binary Data
	$formConsultarUsuario.Icon = [System.Convert]::FromBase64String('
AAABAAIAICAAAAEAIACoEAAAJgAAABAQAAABACAAaAQAAM4QAAAoAAAAIAAAAEAAAAABACAAAAAA
AIAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAA0AAAAVAAAAFgAAABYAAAAWAAAAFgAAABYAAAAW
AAAAFgAAABYAAAAWAAAAFgAAABYAAAAWAAAAFgAAABUAAAANAAAABAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAKwAAAD8AAABDAAAAQwAA
AEMAAABDAAAAQwAAAEMAAABDAAAAQwAAAEMAAABDAAAAQwAAAEMAAABDAAAAPwAAACsAAAANAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABVbW1vE
ZWZm/2ZmZv9mZmb/ZmZm/2ZmZv9mZmb/ZmZm/2VlZf9mZmb/ZmZm/2ZmZv9mZmb/ZWZm/2ZmZv9l
Zmb/WlpaxQAAACUAAAAWAAAAFgAAABYAAAAVAAAADQAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAFmVlZf9dW1v/WFZW/19eXv9ZVlb/WVdX/1lWVv9cW1v/Y2Nj/1xbW/9ZVlb/WVdX
/1lWVv9jYmL/WFZW/11bW/9lZWX/AAAASAAAAEMAAABDAAAAQwAAAD8AAAArAAAADQAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWZGRl/3BubP9jYGD/ZWRk/2RiYv9kYmL/ZGJi/2RkZP9i
Y2P/ZGRk/2RiYv9kYmL/ZGJi/2VkZP9jYGD/cG5t/2VlZf9lZmb/ZmZm/2VmZv9mZmb/ZWZm/1tb
W8QAAAAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABJjY2P/gX5+/2poaP9samr/bWtr
/2hnZ/9jZGT/YmJi/19fXv9iYmL/ZGRk/2hnZ/9ta2v/bGpq/2poaP+Bfn//Y2Rk/1hWVv9ZVlb/
Y2Ji/1hWVv9dW1v/ZWVl/wAAABYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACWNjY/+L
ion/eHZ1/3Vzcv9ubWz/Y2Nj/2BgYP+Kioj/nJya/4eHhv9gYGD/Y2Nj/25tbP91c3L/eHZ1/4uK
if9jY2P/ZGFh/2RiYv9lZGT/Y2Bg/3Bubf9jZGX/AAAAFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAGUVJUa2tsbf+bmpj/h4SE/358e/9hYWH/WVla/9/f3v+RkY//19fV/1paW/9hYWH/
fnx7/4eEg/+amZf/a2tq/2NjY/9oZ2f/bWpr/2xqav9qaGj/gH5//2BiZv8AAAAnAAAAFgAAABYA
AAAWAAAAFgAAABUAAAANAAAABAAAAA4AAAAuOj1DiGVmbP9xcnX/a2pq/11dXf+Dg4P//////4yL
iP/8+/f/gH9+/15fXv9ramr/cnJy/2ZlZf9ycnL/YWFh/2NjY/9ubWz/dXNy/3h1dP+IiIn/WF1o
/gAAAEgAAABDAAAAQwAAAEMAAABDAAAAPwAAACsAAAANAAAAFbN8ENDAggX/pXUV/2JbTv9aW1z/
WFdX/+Pg3///////kYuG///79f/U0cz/XFta/1xcXP9vb2//hoaF/9nZ1/9bW1v/YWFh/358e/+G
hIP/l5aU/2BiZf+WbiH/uX0E/7V7B/+0egj/tHoH/7R7Cf+2fg7/pncWxAAAABUAAAAWt38N////
////////+vv+/4GBgf+Hg3//wuTz/2qqyv9WlLX/Pnye/4intf+GgX3/enh3//b18/+Pjoz//fz5
/4CAfv9eX1//a2pq/29wcP9cW1z/vb7A//////////////////////////////////////+2fg7/
AAAAFgAAABa0ewn//////////////////////6CuwP9Lf6b/eLjY/2qmxv9blrb/Klh7/zNGXf/o
4t7//////5KMh///+/X/1NHL/1taWv9bXFz/ZmNh/+Lg3//////////////////VvKH/////////
/////////////7R7Cf8AAAAWAAAAFrR6B//////////6////+f//////Ol6K/4XK6v+DxOT/ebna
/3Kw0f9mo8f/LFOB/8no9P9sq8v/VpS2/z58nv+GpbP/gX57/4WEg//Uu6D/////////+////vn/
///9/9a8nv////3///74///++f//////tHoH/wAAABYAAAAWtHoI//////////f////4/+Hh4P8x
aJn/ldr6/4nJ6f9+vt7/d7bX/3Cv0P89bpn/V4is/3u62v9qp8b/WpW1/yZUef+Upbj//////93C
o/////3////3////9/////v/1r2e////+/////b////2//////+0egj/AAAAFgAAABa0ewj/////
/9a4lf/fvpn/dHqD/ylml/+f5P//kNLx/4XF5f9+vd3/eLjY/x5LeP9VibH/h8no/3q52/9ysNH/
Y6HG/ytTf//qyKD/3MCf/9e7mv/VuJf/1biX/9e6mv/YvZ3/17qa/9W4lv/Ut5X//////7R7CP8A
AAAWAAAAFrR6CP////////zr////8P+MnrD/NXal/6zz//+d4v//kdTz/4bH6P+CxOL/GkZy/1SN
tv+P0O//f8Dg/3e21/9vr9D/NGqZ/+Xl3//ev5n////w///77P//++z///7w/9a6lv///vD///vr
///76v//////tHoI/wAAABYAAAAWtHoI////////+OL////o/y1VgP8XVIX/HlOA/xlGc/9Acpr/
gsTj/3ey0v8OMmL/JVeG/5nc+/+Hx+f/fr3d/3e32P8WSHn/kKGy/+G+lf//++f///bi///24v//
+ub/1raQ///65v//9uH///bh//////+0egj/AAAAFgAAABa0ewj////////43////+b/AC5q/ypz
of9Gha//Woy0/1Z8pP8wUnz/JUdy/xpIev8NOW3/pu3//5PV9P+Gx+j/gsPi/xVFdf+QorD/5MGT
///85f//9+D///fg///65P/Wt47///rk///33///9t7//////7R7CP8AAAAWAAAAFrR7Cf//////
2bSE/+zCjP8AMG3/J3Gg/0OHsf9SjLP/Woqz/018pv83ZJH/GEZ5/xI/cv8eTHj/QXOa/4LE4/92
stL/CjJk/ytRef/qxJL/27iL/9i1h//YtYf/2LeK/9m4jf/Yt4r/17SG/9ayg///////tHsJ/wAA
ABYAAAAWtXsI///////X2t7/6Obk/wc4cP8VVIb/N4Kv/0SHsf9Jha//P3ei/y1hkP8UQ3b/FUN1
/12RuP9XfaX/MFJ8/yVHcv8YSHv/ATd0/+7EjP/b3+T/19vf/9fb3//Y3OP/2raE/9jc4//X2t7/
1djc//////+1ewj/AAAAFgAAABa0ewj//////9TW1//e3Nr/jJ6x/wAtZv8YV4r/Lnmm/zF4pv8q
bZr/GU+B/xNAcv8wbZv/VI+2/1qLtP9NfKb/N2SR/xVFef8BN3H/7MGG/9nb3f/W19j/1tfY/9bY
2//Zsnz/1tnc/9bW1//T1df//////7R7CP8AAAAWAAAAFrR6CP//////////////////////vsza
/xhFeP8ALWX/ADBo/wAxav8DNGv/FE+B/zmFsv9EibL/SYWv/z92ov8sYZD/D0F1/w4/dv//////
////////////////////////////////////////////////tHoI/wAAABYAAAAWtHoH////////
/////////////////////////////////////////7PB0P8ALmj/GlqM/y97qP8yeaf/KW2a/xVN
gP8HOXH/b4CS//////+joqH/jIuK/6KhoP//////oqGh/4yLiv+hoJ////////////+0egf/AAAA
FgAAABa0egf/////////+/+Af37/hYOC/4aEg/+IhYT/iYaE/4iGhP+HhIL//////7/K0f8LOWz/
ADRs/wM0bf8AMmz/ET5x/257h/+Xko7//////42Liv+SkI//jYuK//////+Ni4r/kpCP/4yKiP//
/////////7R6B/8AAAAWAAAAFrR6CP////////zx///+8/////X////1////9f////X////1////
8////vL////4/6ylnf+Zk4v/samg//////+uqJ//k4+K/6Sgm/////r/oZ+b/4uKh/+hn5v////6
/6Gfm/+Liof/oJ6Z////9f//////tHoI/wAAABYAAAAWtHoI////////+Oj///jo///56f//+en/
//np///56f//+en///jo///46P///Ov////y////9v////P////w////8/////X////y////7///
//L////1////8v///+/////y////9f////H///zr//////+0egj/AAAAFgAAABa0egj////////2
4P//+eL///vk///75P//++T///vk///75P//+eP///bh///65P+gnJX/jImE/6Gdlf///+n/oZ2V
/4yJhP+hnZX////p/6Gdlf+MiYT/oZ2V////6f+hnZX/jImE/6CclP//++T//////7R6CP8AAAAW
AAAAFrR6CP////////ba/399eP+DgXz/hIJ8/4SCfP+Egnz/g4F8/399ef//9tv///re/4uHgf+R
job/jImC////5P+MiYL/kY6G/4yJgv///+T/jImC/5GOhv+MiYL////k/4yJgv+Rjob/i4eA///6
3f//////tHoI/wAAABYAAAAWtHoI////////8dH///TU///31v//99b///fW///31v//99b///TU
///y0v//9dX/n5mN/4qGf/+gmo7///va/6Cajv+Khn//oJqO///72v+gmo7/ioZ//6Cajv//+9r/
oJqO/4qGf/+fmYz///XU//////+0egj/AAAAFgAAABW0ewn////////vzf//783///DP///wz///
8M////DP///wz///787//+/O///wz///9NL///bU///00v//89H///TS///21P//9NL///PR///0
0v//9tT///TS///z0f//9NL///bU///00v//8c///////7R7Cf8AAAAVAAAADbZ+Dv//////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////tn4O/wAAAA0A
AAAEtYEYtLZ+Dv+0ewn/tHoI/7R6CP+0egj/tHoI/7R6CP+0egj/tHoI/7R6CP+0egj/tHoI/7R6
CP+0egj/tHoI/7R6CP+0egj/tHoI/7R6CP+0egj/tHoI/7R6CP+0egj/tHoI/7R6CP+0egj/tHsJ
/7Z+Dv+1gRi0AAAABAAAH/8AAB//AAAAfwAAAH8AAAB/AAAAfwAAAH8AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAABAAAAAgAAAAAQAgAAAAAABABAAAAAAAAAAA
AAAAAAAAAAAAAAAAADAAAAAzAAAAMwAAADMAAAAzAAAAMwAAADMAAAAzAAAALgAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAABjY2PyY2Nj/2NjZP9kZGT/YmJi/2NkZP9jY2P/Y2Nj/2JiYuwAAAAz
AAAAMwAAAC4AAAAAAAAAAAAAAAAAAAAAaGdo/3h2df94dXP/amlo/2JiYv92dXX/eHRz/3l2df9i
YmL/Y2Nj/2JjZf9ZXmnsAAAAMwAAADMAAAAzAAAAMGBjaP+vra3/ZWZl/3x8fP8tLCz/q6ur/15e
Xf+wrqv/X19f/3l1dP93dXb/V1xj/76BBv+2fAj/tn4O/7eCGfKddy3/aWxy/3Nyc//o5+f/SEdG
/+jn5/9oaGb/cXFx/4ODg/9eX17/rauq/09SV/////////////////+2fg7/vYIL//L3//90cXL/
z+Hq/ycgHf/K19//gH18/1JRUP/o5+f/ZWVl/2dqbf+tnYz/////////////////tHsJ/7d9Cv//
////7Mmk/5DE3P9kpcj/Woql/9jl6/8qIh//x9bf/2tmYP/Ls5f/4cak/9m+nP/VuZf//////7R7
CP+2fAn//////7LEy/+L0/b/fb7g/2qrzf9cmL3/aarM/2iWrv////T////1/9u9mP////D///3s
//////+0ewj/t3wJ//////8bT3v/h8zt/5LV9P+Cw+P/Ezho/4TH5/9mqs//k5SN/+K+jf/auo7/
2LaJ/9azhf//////tHsJ/7d9Cf//////ADBp/yxxov9djbj/WoSq/wYjVP+Z3vz/gMTl/ws0aP/k
5ef/27WB/9TZ3//T19z//////7V7CP+2fAn//////z9slP8le7D/RIe3/yxYhv8YO2r/YJK9/1eD
q/8AHFP///////////////////////////+1ewj/tnwJ//////+KhID/GFGA/whQiP8DOG3/J3iu
/0OJuv8jU4X/GzJa////9v9/fnz////w/319e///////tXsJ/7V7Cf/////////k////5////+n/
//7g/zJokv8GUIn/LlqB///53v///uL///vg///53///+t///////7V7Cf+1fAn//////4N/dv+H
gnj/iYN5/4qDeP///9n/kYd5////2f+Ef3b///fU/357c///9dP/fnpy//////+1fAn/tn4O////
////////////////////////////////////////////////////////////////////////tn4O
/7mEGe+2fg7/tXwK/7V8Cf+1fAn/tXwJ/7V7Cf+1fAn/tXsJ/7V8Cf+1ewn/tXwJ/7V7Cf+1fAr/
tn4O/7mEGe8AfwAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA')
	#endregion
	$formConsultarUsuario.Margin = '20, 16, 20, 16'
	$formConsultarUsuario.MaximizeBox = $False
	$formConsultarUsuario.Name = 'formConsultarUsuario'
	$formConsultarUsuario.StartPosition = 'CenterScreen'
	$formConsultarUsuario.Text = 'Consultar Usuario'
	$formConsultarUsuario.add_Load($formConsultarUsuario_Load)
	#
	# Usuario
	#
	$Usuario.Anchor = 'Top, Left, Right'
	$Usuario.Location = '141, 4'
	$Usuario.Margin = '8, 7, 8, 7'
	$Usuario.Name = 'Usuario'
	$Usuario.Size = '244, 36'
	$Usuario.TabIndex = 6
	$Usuario.add_KeyPress($Usuario_KeyPress)
	#
	# statusstrip1
	#
	$statusstrip1.Enabled = $False
	$statusstrip1.ImageScalingSize = '36, 36'
	[void]$statusstrip1.Items.Add($Etiqueta2)
	[void]$statusstrip1.Items.Add($progressbar)
	$statusstrip1.Location = '0, 426'
	$statusstrip1.Name = 'statusstrip1'
	$statusstrip1.Padding = '2, 0, 35, 0'
	$statusstrip1.Size = '562, 42'
	$statusstrip1.TabIndex = 4
	$statusstrip1.Text = 'statusstrip1'
	#
	# toolstrip1
	#
	$toolstrip1.BackColor = 'Control'
	$toolstrip1.GripStyle = 'Hidden'
	$toolstrip1.ImageScalingSize = '36, 36'
	[void]$toolstrip1.Items.Add($Label1)
	[void]$toolstrip1.Items.Add($Separador1)
	[void]$toolstrip1.Items.Add($Buscar)
	$toolstrip1.Location = '0, 0'
	$toolstrip1.Name = 'toolstrip1'
	$toolstrip1.Padding = '0, 0, 2, 0'
	$toolstrip1.RenderMode = 'System'
	$toolstrip1.Size = '562, 44'
	$toolstrip1.TabIndex = 3
	$toolstrip1.Text = 'toolstrip1'
	#
	# Label1
	#
	$Label1.Font = 'Segoe UI, 9pt, style=Bold'
	$Label1.Name = 'Label1'
	$Label1.Size = '123, 41'
	$Label1.Text = 'Usuario:'
	#
	# Buscar
	#
	#region Binary Data
	$Buscar.Image = [System.Convert]::FromBase64String('
iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACx
jwv8YQUAAAAJcEhZcwAAITcAACE3ATNYn3oAAAKfSURBVDhPnZJdSJNRHMZfCMQP6KaLDIsiCSGm
iHUhdNFFUd35FSyGbrIv3y292Obm1t7N6Ttbs4wySYO8Cb3Zy0wyXQnbTZKVhhfzM8WpKevDKMSU
Pp/OOTNaVjc98PA/57z/38P5H15utzf0fqd7AOlCP9KS7fx3pb2UoSxHF/8rynI0lcpWL8Le6IND
9MMuNmOGnDl811m11XsxvglYnG5EPwLmC27GUJajV6JaJo4TvyZe+A608gXwF6egQZGH+U/AEjlb
+ALEyDr2mRIkgLDkBokRPN5meEoycak4FTWFO9Bjz8Gg/wSayrKhKMjCBukR3PX4QKrT5WLMbwFt
1cfR6zyEkO8kLp6TwXgsE+HWSkiiHGV7OdazXakswBViG0M+hzsmGR60VCDgVeBsdgq+zt/CypAH
/NEMxFeW0dA/i9jMOOamooxJBAiJAGdRFt6N+rA+0YqXjxrBF+5CfNiLsYAeLW030BJZwtXBF/AP
TKOpb5Ixac77v0YYGbqHjehlLERceC4ZEe4ox2jAgJ6bPNbJd/L46AjPsjdY/UYJegMSkL41QtfT
VcwNXcOTbi26mxV4uzKN/QcPIzY5jEr9ebT3jaDr8SJuR2bQ/nCCMSwgozEMbK7BbKrFm8Ux7DuQ
g9jUMwguD4pLShGPv4JOp0ONsQpXOoMM/Ck2Qm5dJ8zVBljMFtZ86vQZVvU8D5PJBFEUoVQpEZCC
kJcWbaEJsT+R11QiGLwLnV4HQRAgk+VCkiRUKJWQenqhUqlQa3XAZq2DplyOlIYIUsm7UXiPJ7TG
8VU8rDY7LFY7eIMRarUaVqsNllo7OXewvUajgU6jRpVSvspx3JEk53Pk4xpt0FJrtQzQajUMoib7
ZCiP+A/lEyenbvdfoYQ47gfDuY22zZ9TUAAAAABJRU5ErkJggg==')
	#endregion
	$Buscar.ImageTransparentColor = 'Magenta'
	$Buscar.Name = 'Buscar'
	$Buscar.Size = '133, 41'
	$Buscar.Text = 'Buscar'
	$Buscar.add_Click($Buscar_Click)
	#
	# Etiqueta2
	#
	$Etiqueta2.Name = 'Etiqueta2'
	$Etiqueta2.Size = '129, 37'
	$Etiqueta2.Text = 'Progreso:'
	#
	# progressbar
	#
	$progressbar.Name = 'progressbar'
	$progressbar.Size = '375, 36'
	$progressbar.Step = 12
	#
	# Separador1
	#
	$Separador1.AutoSize = $False
	$Separador1.Name = 'Separador1'
	$Separador1.Size = '260, 44'
	$toolstrip1.ResumeLayout()
	$statusstrip1.ResumeLayout()
	$formConsultarUsuario.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formConsultarUsuario.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formConsultarUsuario.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formConsultarUsuario.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$formConsultarUsuario.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $formConsultarUsuario.ShowDialog()

}
#endregion Source: MainForm.psf

#Start the application
Main ($CommandLine)
